name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
      
    runs-on: Windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          powershell.exe -NoProfile -InputFormat None -ExecutionPolicy AllSigned -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://dl-cli.pstmn.io/install/win64.ps1'))"
      - name: Verify Postman CLI Installation
        run: postman --version
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run Postman Collection
        uses: actions/postman/collection-runner@v1
        with:
          collection: "9578175-59faff03-6266-4623-a317-03587212e823"
          environment: "9578175-44037ed4-9749-40ba-9ca9-f18e098f34c5"
          # Replace with your actual mock server URL
          base-url: "https://7e70761e-fa25-4cbb-b673-010fbba77d97.mock.pstmn.io"  
     
